package tara.dsl;

import tara.language.model.Tag;

import java.util.Locale;
import static tara.language.semantics.constraints.RuleFactory.*;

public class Tafat extends Tara {
	public Tafat() {
		in("").def(context("").allow(multiple("Agent"), multiple("Entity"), multiple("Behavior", Tag.FACET), multiple("Aspect", Tag.FACET), multiple("Behavior", Tag.FACET), multiple("Aspect", Tag.FACET), multiple("Knol"), multiple("HeatMap", Tag.MAIN, Tag.TERMINAL_INSTANCE), multiple("HeatMap", Tag.MAIN, Tag.TERMINAL_INSTANCE), multiple("Action", Tag.PROTOTYPE, Tag.FEATURE_INSTANCE), multiple("ConditionalAction", Tag.PROTOTYPE, Tag.FEATURE_INSTANCE), multiple("StateChart", Tag.PROTOTYPE), multiple("Task", Tag.PROTOTYPE, Tag.FEATURE_INSTANCE), multiple("StartJob", Tag.FEATURE_INSTANCE), multiple("RecurrentJob", Tag.FEATURE_INSTANCE), multiple("EndJob", Tag.FEATURE_INSTANCE), multiple("StartJob", Tag.FEATURE_INSTANCE), multiple("RecurrentJob", Tag.FEATURE_INSTANCE), multiple("EndJob", Tag.FEATURE_INSTANCE), multiple("Job", Tag.FEATURE_INSTANCE), multiple("TableFunction", Tag.FEATURE_INSTANCE), multiple("PointSet", Tag.FEATURE_INSTANCE), multiple("Map", Tag.FEATURE_INSTANCE), single("Simulation", Tag.REQUIRED, Tag.SINGLE, Tag.TERMINAL_INSTANCE, Tag.MAIN), name()).doc("tafat.Tafat", 0, ""));
		in("Output").def(context("Concept").allow(multiple("Output.Export", Tag.TERMINAL_INSTANCE), multiple("Output.Plot", Tag.TERMINAL_INSTANCE), multiple("Output.Export", Tag.TERMINAL_INSTANCE), multiple("Output.Plot", Tag.TERMINAL_INSTANCE), name()).require(_parameter("language", "string", false, 0, "", "TERMINAL"), _parameter("simulationId", "string", false, 1, "", "TERMINAL")).assume(isTerminalInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Output.tara", 3, ""));
		in("Output.Export").def(context("Concept").allow(parameter("path", "native", false, 3, "StashPath#public String stashPath()", "FINAL", "TERMINAL"), parameter("buildStash", "native", false, 4, "Stash#public List<tara.io.Case> build()", "FINAL", "TERMINAL"), parameter("toCase", "native", false, 5, "MemberToCase#public tara.io.Case toCase(tafat.engine.output.Member member)", "FINAL", "TERMINAL"), name()).require(_parameter("label", "string", false, 0, "", "FINAL", "TERMINAL"), _parameter("collect", "native", false, 1, "Collect#public List<? extends tara.magritte.Layer> collect()", "FINAL", "TERMINAL"), _parameter("extract", "native", false, 2, "ExtractMember#public void extract(tafat.engine.output.Member member, tara.magritte.Layer layer)", "FINAL", "TERMINAL")).assume(isTerminalInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Output.tara", 13, ""));
		in("Output.Plot").def(context("Concept").allow(parameter("path", "native", false, 4, "StashPath#public String stashPath()", "FINAL", "TERMINAL"), parameter("buildStash", "native", false, 5, "Stash#public List<tara.io.Case> build()", "FINAL", "TERMINAL"), parameter("toCase", "native", false, 6, "FactToCase#public tara.io.Case toCase(tafat.engine.output.Fact fact)", "FINAL", "TERMINAL"), name()).require(_parameter("label", "string", false, 0, "", "FINAL", "TERMINAL"), _parameter("collect", "native", false, 1, "Collect#public List<? extends tara.magritte.Layer> collect()", "FINAL", "TERMINAL"), _parameter("timeScale:word", new String[]{"Years", "Quarters", "Months", "Weeks", "Days", "Hours", "Minutes", "Seconds"}, false, 2, "TimeScale##Tafat", "FINAL", "TERMINAL"), _parameter("extract", "native", false, 3, "ExtractFact#public void extract(tafat.engine.output.Fact fact, tara.magritte.Layer layer)", "FINAL", "TERMINAL")).assume(isTerminalInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Output.tara", 35, ""));
		in("Simulation").def(context("Concept").allow(single("Output", Tag.TERMINAL_INSTANCE, Tag.SINGLE), name()).require(_parameter("from", "date", false, 0, "", "TERMINAL"), _parameter("to", "date", false, 1, "", "TERMINAL")).assume(isTerminalInstance(), isMain()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Main.tara", 5, ""));
		in("Agent").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Main.tara", 8, ""));
		in("Entity").def(context("Concept").allow(multiple("Entity"), multiple("Entity.Feature", Tag.FEATURE), name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Main.tara", 10, ""));
		in("Entity.Feature").def(context("Concept").allow(name()).assume(isFeature()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Main.tara", 12, ""));
		in("Behavior").def(context("Concept").allow(multiple("Behavior.Start", Tag.PROTOTYPE, Tag.FEATURE_INSTANCE, Tag.FINAL), multiple("Behavior.Knol", Tag.PROTOTYPE, Tag.FEATURE_INSTANCE, Tag.FINAL), multiple("Action", Tag.PROTOTYPE, Tag.FEATURE_INSTANCE, Tag.FINAL), multiple("ConditionalAction", Tag.PROTOTYPE, Tag.FEATURE_INSTANCE, Tag.FINAL), multiple("EquationSystem", Tag.FEATURE_INSTANCE, Tag.TERMINAL_INSTANCE, Tag.FINAL), multiple("StateChart", Tag.PROTOTYPE, Tag.FINAL), multiple("Task", Tag.PROTOTYPE, Tag.FEATURE_INSTANCE, Tag.FINAL), multiple("TableFunction", Tag.FEATURE_INSTANCE, Tag.FINAL), multiple("PointSet", Tag.FEATURE_INSTANCE, Tag.FINAL), multiple("Job", Tag.FEATURE_INSTANCE, Tag.FINAL), multiple("Map", Tag.FEATURE_INSTANCE, Tag.FINAL), parameter("step", "integer", false, 0, "", "TERMINAL"), name()).assume(isFacet()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Main.tara", 15, ""));
		in("Behavior.Start").def(context("Concept").allow(name()).require(_parameter("start", "native", false, 0, "Action#public void execute()")).assume(isPrototype(), isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Main.tara", 17, ""));
		in("Behavior.Knol").def(context("Concept").allow(name()).assume(isPrototype(), isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Main.tara", 18, ""));
		in("Aspect").def(context("Concept").allow(name()).assume(isFacet()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Main.tara", 28, ""));
		in("Knol").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Main.tara", 30, ""));
		in("HeatMap").def(context("Concept").allow(multiple("HeatMap.Region", Tag.TERMINAL_INSTANCE), name()).require(_parameter("path", "string", false, 0, "", "TERMINAL")).assume(isMain(), isTerminalInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Main.tara", 33, ""));
		in("HeatMap.Region").def(context("Concept").allow(name()).require(_parameter("coordinates", "double", true, 0, "", "TERMINAL"), _parameter("calculate", "native", false, 1, "Function#public double calculate()", "TERMINAL")).assume(isTerminalInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\Main.tara", 35, ""));
		in("Action").def(context("Concept").allow(name()).require(_parameter("action", "native", false, 0, "Action#public void execute()")).assume(isPrototype(), isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 3, ""));
		in("ConditionalAction").def(context("Concept").allow(parameter("condition", "native", false, 0, "Check#public boolean check()"), name()).require(_parameter("action", "native", false, 1, "Action#public void execute()")).assume(isPrototype(), isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 6, ""));
		in("EquationSystem").def(context("Concept").allow(multiple("EquationSystem.Stock", Tag.TERMINAL_INSTANCE), multiple("EquationSystem.Flow", Tag.TERMINAL_INSTANCE), multiple("EquationSystem.Stock", Tag.TERMINAL_INSTANCE), multiple("EquationSystem.Flow", Tag.TERMINAL_INSTANCE), parameter("solver:word", new String[]{"Euler"}, false, 0, "", "TERMINAL"), parameter("step", "double", false, 1, "", "TERMINAL"), name()).assume(isFeatureInstance(), isTerminalInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 10, ""));
		in("EquationSystem.Stock").def(context("Concept").allow(name()).require(_parameter("function", "native", false, 0, "Function#public double calculate()", "TERMINAL")).assume(isTerminalInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 15, ""));
		in("EquationSystem.Flow").def(context("Concept").allow(name()).require(_parameter("function", "native", false, 0, "Function#public double calculate()", "TERMINAL")).assume(isTerminalInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 16, ""));
		in("StateChart").def(context("Concept").allow(multiple("StateChart.State", Tag.PROTOTYPE), multiple("StateChart.Transition"), parameter("message", "string", false, 0, ""), parameter("receiveMessage", "native", false, 1, "Message#public void receiveMessage(String message)"), parameter("current", new String[]{"StateChart.State", "StateChart"}, false, 2, ""), name()).assume(isPrototype()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 18, ""));
		in("StateChart.State").def(context("Concept").allow(multiple("StateChart.State", Tag.PROTOTYPE), multiple("StateChart.Transition"), multiple("StateChart.State.EntryAction"), multiple("StateChart.State.ExitAction"), multiple("StateChart.State.EntryAction"), multiple("StateChart.State.ExitAction"), parameter("message", "string", false, 0, ""), parameter("receiveMessage", "native", false, 1, "Message#public void receiveMessage(String message)"), parameter("current", new String[]{"StateChart.State", "StateChart"}, false, 2, ""), name()).assume(isPrototype()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 22, ""));
		in("StateChart.State.EntryAction").def(context("Concept").allow(name()).require(_parameter("action", "native", false, 0, "Action#public void execute()")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 25, ""));
		in("StateChart.State.ExitAction").def(context("Concept").allow(name()).require(_parameter("action", "native", false, 0, "Action#public void execute()")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 26, ""));
		in("StateChart.Transition").def(context("Concept").allow(single("StateChart.Transition.Condition", Tag.SINGLE), single("StateChart.Transition.Timeout", Tag.SINGLE), single("StateChart.Transition.After", Tag.SINGLE), single("StateChart.Transition.Rate", Tag.SINGLE), single("StateChart.Transition.Message", Tag.SINGLE), single("StateChart.Transition.Condition", Tag.SINGLE), single("StateChart.Transition.Timeout", Tag.SINGLE), single("StateChart.Transition.After", Tag.SINGLE), single("StateChart.Transition.Rate", Tag.SINGLE), single("StateChart.Transition.Timeout", Tag.SINGLE), single("StateChart.Transition.After", Tag.SINGLE), single("StateChart.Transition.Rate", Tag.SINGLE), single("StateChart.Transition.Message", Tag.SINGLE), parameter("action", "native", false, 2, "Action#public void execute()"), name()).require(_parameter("from", new String[]{"StateChart.State"}, false, 0, ""), _parameter("to", new String[]{"StateChart.State"}, false, 1, "")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 27, ""));
		in("StateChart.Transition.Condition").def(context("Concept").allow(name()).require(_parameter("check", "native", false, 0, "Check#public boolean check()")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 33, ""));
		in("StateChart.Transition.Timeout").def(context("Concept").allow(parameter("timeLeft", "measure", false, 0, "Time[minute, minutes, m]"), parameter("check", "native", false, 1, "Check#public boolean check()"), parameter("activate", "native", false, 2, "Action#public void execute()"), name()).require(_parameter("timeout", "native", false, 3, "Timeout#public int calculate()", "FINAL")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 38, ""));
		in("StateChart.Transition.After").def(context("Concept").allow(parameter("timeLeft", "measure", false, 0, "Time[minute, minutes, m]"), parameter("check", "native", false, 1, "Check#public boolean check()"), parameter("activate", "native", false, 2, "Action#public void execute()"), name()).require(_parameter("fixedTime", "measure", false, 3, "Time[minute, minutes, m]", "FINAL")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 41, ""));
		in("StateChart.Transition.Rate").def(context("Concept").allow(parameter("timeLeft", "measure", false, 0, "Time[minute, minutes, m]"), parameter("check", "native", false, 1, "Check#public boolean check()"), parameter("activate", "native", false, 2, "Action#public void execute()"), name()).require(_parameter("times", "integer", false, 3, "times##Tafat"), _parameter("unit", "integer", false, 4, "")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 44, ""));
		in("StateChart.Transition.Message").def(context("Concept").allow(parameter("check", "native", false, 1, "Check#public boolean check()"), name()).require(_parameter("expectedMessage", "string", false, 0, "")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 47, ""));
		in("Task").def(context("Concept").allow(multiple("Task", Tag.PROTOTYPE, Tag.FEATURE_INSTANCE), multiple("StartJob", Tag.FEATURE_INSTANCE), multiple("RecurrentJob", Tag.FEATURE_INSTANCE), multiple("EndJob", Tag.FEATURE_INSTANCE), multiple("Task.StartAction"), multiple("Task.RecurrentAction"), multiple("Task.EndAction"), multiple("Task.StartAction"), multiple("Task.RecurrentAction"), multiple("Task.EndAction"), single("Task.End", Tag.SINGLE), single("Task.Duration", Tag.SINGLE), single("Task.End", Tag.SINGLE), single("Task.Duration", Tag.SINGLE), parameter("days:word", new String[]{"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"}, true, 0, "DayOfWeek##Tafat"), parameter("check", "native", false, 1, "Check#public boolean check()"), parameter("isTodayScheduled", "native", false, 2, "Check#public boolean check()"), parameter("program", "native", false, 3, "Action#public void execute()"), parameter("launchedDate", "date", false, 4, ""), name()).require(_single("Task.Start")).assume(isPrototype(), isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 51, ""));
		in("Task.Start").def(context("Concept").allow(parameter("deviation", "measure", false, 1, "Time[minute, minutes, m]"), parameter("scheduledTime", "time", false, 2, ""), name()).require(_parameter("start", "time", false, 0, "")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 68, ""));
		in("Task.End").def(context("Concept").allow(parameter("deviation", "measure", false, 1, "Time[minute, minutes, m]"), name()).require(_parameter("end", "time", false, 0, "")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 73, ""));
		in("Task.Duration").def(context("Concept").allow(parameter("deviation", "measure", false, 1, "Time[minute, minutes, m]"), name()).require(_parameter("duration", "measure", false, 0, "Time[minute, minutes, m]")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 76, ""));
		in("Task.StartAction").def(context("Concept").allow(name()).require(_parameter("action", "native", false, 0, "Action#public void execute()")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 83, ""));
		in("Task.RecurrentAction").def(context("Concept").allow(name()).require(_parameter("action", "native", false, 0, "Action#public void execute()")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 84, ""));
		in("Task.EndAction").def(context("Concept").allow(name()).require(_parameter("action", "native", false, 0, "Action#public void execute()")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 85, ""));
		in("StartJob").def(context("Concept").allow(name()).require(_parameter("job", new String[]{"Job"}, true, 0, "")).assume(isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 89, ""));
		in("RecurrentJob").def(context("Concept").allow(name()).require(_parameter("job", new String[]{"Job"}, true, 0, "")).assume(isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 90, ""));
		in("EndJob").def(context("Concept").allow(name()).require(_parameter("job", new String[]{"Job"}, true, 0, "")).assume(isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 91, ""));
		in("Job").def(context("Concept").allow(multiple("Job", Tag.FEATURE_INSTANCE), multiple("StartJob", Tag.FEATURE_INSTANCE), multiple("RecurrentJob", Tag.FEATURE_INSTANCE), multiple("EndJob", Tag.FEATURE_INSTANCE), multiple("Job.StartAction"), multiple("Job.RecurrentAction"), multiple("Job.EndAction"), multiple("Job.StartAction"), multiple("Job.RecurrentAction"), multiple("Job.EndAction"), single("Job.Start", Tag.SINGLE), single("Job.Duration", Tag.SINGLE), name()).assume(isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 93, ""));
		in("Job.Start").def(context("Concept").allow(parameter("deviation", "measure", false, 1, "Time[minute, minutes, m]"), name()).require(_parameter("start", "measure", false, 0, "Time[minute, minutes, m]")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 94, ""));
		in("Job.Duration").def(context("Concept").allow(parameter("deviation", "measure", false, 1, "Time[minute, minutes, m]"), name()).require(_parameter("duration", "measure", false, 0, "Time[minute, minutes, m]")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 97, ""));
		in("Job.StartAction").def(context("Concept").allow(name()).require(_parameter("action", "native", false, 0, "Action#public void execute()")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 104, ""));
		in("Job.RecurrentAction").def(context("Concept").allow(name()).require(_parameter("action", "native", false, 0, "Action#public void execute()")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 105, ""));
		in("Job.EndAction").def(context("Concept").allow(name()).require(_parameter("action", "native", false, 0, "Action#public void execute()")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 106, ""));
		in("TableFunction").def(context("Concept").allow(single("TableFunction.NoneInterpolation", Tag.SINGLE), single("TableFunction.LinearInterpolation", Tag.SINGLE), single("TableFunction.PolynomialInterpolation", Tag.SINGLE), single("TableFunction.SplineInterpolation", Tag.SINGLE), single("TableFunction.StepInterpolation", Tag.SINGLE), single("TableFunction.NoneInterpolation", Tag.SINGLE), single("TableFunction.LinearInterpolation", Tag.SINGLE), single("TableFunction.PolynomialInterpolation", Tag.SINGLE), single("TableFunction.SplineInterpolation", Tag.SINGLE), single("TableFunction.StepInterpolation", Tag.SINGLE), single("TableFunction.NoneExtrapolation", Tag.SINGLE), single("TableFunction.CustomExtrapolation", Tag.SINGLE), single("TableFunction.NearestPointExtrapolation", Tag.SINGLE), single("TableFunction.RepeatSeriesExtrapolation", Tag.SINGLE), single("TableFunction.LinearExtrapolation", Tag.SINGLE), single("TableFunction.PolynomialExtrapolation", Tag.SINGLE), single("TableFunction.SplineExtrapolation", Tag.SINGLE), single("TableFunction.StepExtrapolation", Tag.SINGLE), single("TableFunction.NoneExtrapolation", Tag.SINGLE), single("TableFunction.CustomExtrapolation", Tag.SINGLE), single("TableFunction.NearestPointExtrapolation", Tag.SINGLE), single("TableFunction.RepeatSeriesExtrapolation", Tag.SINGLE), single("TableFunction.LinearExtrapolation", Tag.SINGLE), single("TableFunction.PolynomialExtrapolation", Tag.SINGLE), single("TableFunction.SplineExtrapolation", Tag.SINGLE), single("TableFunction.StepExtrapolation", Tag.SINGLE), name()).require(_parameter("pointSet", new String[]{"PointSet"}, false, 0, "")).assume(isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 108, ""));
		in("TableFunction.NoneInterpolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 111, ""));
		in("TableFunction.LinearInterpolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 112, ""));
		in("TableFunction.PolynomialInterpolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 113, ""));
		in("TableFunction.SplineInterpolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 114, ""));
		in("TableFunction.StepInterpolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 115, ""));
		in("TableFunction.NoneExtrapolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 117, ""));
		in("TableFunction.CustomExtrapolation").def(context("Concept").allow(name()).require(_parameter("function", "native", false, 0, "Function#public double calculate()")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 118, ""));
		in("TableFunction.NearestPointExtrapolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 119, ""));
		in("TableFunction.RepeatSeriesExtrapolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 120, ""));
		in("TableFunction.LinearExtrapolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 121, ""));
		in("TableFunction.PolynomialExtrapolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 122, ""));
		in("TableFunction.SplineExtrapolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 123, ""));
		in("TableFunction.StepExtrapolation").def(context("Concept").allow(name()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 124, ""));
		in("PointSet").def(context("Concept").allow(multiple("PointSet.Point", Tag.FINAL), multiple("PointSet.X", Tag.SINGLE, Tag.FINAL), multiple("PointSet.Y", Tag.SINGLE, Tag.FINAL), multiple("PointSet.Point", Tag.FINAL), single("PointSet.X", Tag.SINGLE, Tag.FINAL), single("PointSet.Y", Tag.SINGLE, Tag.FINAL), name()).assume(isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 126, ""));
		in("PointSet.Point").def(context("Concept").allow(name()).require(_parameter("x", "double", false, 0, "", "FINAL"), _parameter("y", "double", false, 1, "", "FINAL")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 128, ""));
		in("PointSet.X").def(context("Concept").allow(name()).require(_parameter("values", "double", true, 0, "", "FINAL")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 129, ""));
		in("PointSet.Y").def(context("Concept").allow(name()).require(_parameter("values", "double", true, 0, "", "FINAL")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 130, ""));
		in("Map").def(context("Concept").allow(multiple("Map.Entry"), parameter("get", "native", false, 0, "Get#public double get(String key)", "FINAL"), name()).assume(isFeatureInstance()).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 132, ""));
		in("Map.Entry").def(context("Concept").allow(name()).require(_parameter("key", "string", false, 0, ""), _parameter("value", "double", false, 1, "")).doc("D:\\Users\\jevora\\repositories\\tafat\\Base\\model\\ModellingMechanisms.tara", 134, ""));
	}

	@Override
	public String languageName() {
		return "Tafat";
	}

	@Override
    public Locale locale() {
        return Locale.ENGLISH;
    }

    @Override
    public boolean isTerminalLanguage() {
        return false;
    }
}
